name: CI/CD with Docker Compose

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Checkout repository

      - name: Build and Test with Docker Compose
        run: |
          docker-compose build  # Build services
          docker-compose up -d  # Start services in detached mode
          sleep 60  # Wait for services to initialize
          curl http://localhost:8000/docs  # Test FastAPI endpoint
